export type RootStackParamList = {
  Signup: undefined;
  Phone: undefined;
  Otp: undefined;
  Name: undefined;
  Birthday: undefined;
  Gender: undefined;
  Vibe: undefined;
  ProfilePhoto: undefined;
  Highlights: { mode?: 'edit' } | undefined;
  Verify: undefined;
  SelfieCheck: undefined;
  Lock: undefined;
  Board: undefined;
  Detail: { id: string };
  MyPlans: undefined;
  PlanManage: { id: string };
  RequesterChat: { planId: string; requesterId: string; name: string };
  RequesterProfile: { planId: string; requesterId: string };
  Create: undefined;
  Sent: undefined;
  Queue: undefined;
  ChatList: undefined;
  Chat: { id: string };
  Profile: undefined;
  Settings: undefined;
  Review: undefined;
  Filed: undefined;
};
