export type RootStackParamList = {
  Signup: undefined;
  Auth: undefined;
  Name: undefined;
  Birthday: undefined;
  Gender: undefined;
  Vibe: undefined;
  ProfilePhoto: undefined;
  Highlights: { mode?: 'edit' } | undefined;
  Verify: undefined;
  SelfieCheck: undefined;
  Lock: undefined;
  Board: undefined;
  Detail: { id: string };
  MyPlans: undefined;
  PlanManage: { id: string };
  RequesterChat: { planId?: string; requesterId: string; name: string };
  RequesterProfile: { userId: string };
  MyReviews: undefined;
  SentRequests: undefined;
  Create: undefined;
  ChatList: undefined;
  Chat: { id: string };
  Profile: undefined;
  EditProfile: undefined;
  Settings: undefined;
  Safety: undefined;
  Review: { planId: string };
  Filed: { rated: number; firstName?: string | null; stars?: number | null; withNote?: boolean } | undefined;
  SearchFilters: undefined;
  Notifications: undefined;
  ReviewDetail: { reviewId: string };
  ReportReview: { reviewId: string };
};
